services:
  healthy-url:
    build: .
    env_file:
      - .env
    depends_on:
      - cassandra
    networks:
      - healthy-url-network

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=healthy-url-cluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - healthy-url-network

networks:
  healthy-url-network:
    driver: bridge